name: arrow
on:
  push:
    paths:
      - arrow/**
  pull_request:
    paths:
      - arrow/**
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-16.04
    container: centos:6
    steps:
      - uses: saudet/javacpp-presets/.github/actions/deploy-centos@master
  macosx-x86_64:
    runs-on: macos-10.15
    steps:
      - uses: saudet/javacpp-presets/.github/actions/deploy-macosx@master
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: saudet/javacpp-presets/.github/actions/deploy-windows@master
  redeploy:
    needs: [linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-16.04
    steps:
      - uses: saudet/javacpp-presets/.github/actions/redeploy@master
